[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
    /(
        \.eggs
        | \.git
        | \.hg
        | \.mypy_cache
        | \.nox
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
    )/
'''

[tool.pytest.ini_options]
pythonpath = "src/"